const data = [
  {
    id: 1,
    title: "Zak Norris",
    description: "...",
    imgAsset: "Studentbb copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 1536,
    height: 2048,
    scale: 2,
    trophie_icon: "view_carousel",
    isObj: true
  },
  {
    id: 2,
    title: "Maddie Watson",
    description: "...",
    imgAsset: "Maddie1 copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2867,
    height: 4096,
    scale: 1,
    trophie_icon: "star_half",
    isObj: true
  },
  {
    id: 3,
    title: "Liam Kelleher - All Our Own Crafts",
    description: "...",
    imgAsset: "All_Our_Own_Crafts copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 6000,
    height: 2550,
    scale: 1,
    trophie_icon: "build",
    isObj: true
  },
  {
    id: 4,
    title: "Bethany O'Sullivan",
    description: "...",
    imgAsset: "iPad_1 2 copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 4096,
    height: 2867,
    scale: 1,
    trophie_icon: "local_florist",
    isObj: true
  },
  {
    id: 5,
    title: "Danny Balcombe",
    description: "...",
    imgAsset: "Scream_iPad copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2867,
    height: 4096,
    scale: 1,
    trophie_icon: "wallpaper",
    isObj: true
  },
  {
    id: 6,
    title: "Liam Kelleher - When Robots Attack",
    description: "...",
    imgAsset: "When_Robots_Attack_-_Proteus copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2867,
    height: 4096,
    scale: 1,
    trophie_icon: "format_size",
    isObj: true
  },
  {
    id: 7,
    title: "Emily McBrayne",
    description: "...",
    imgAsset: "Emily_Mcbrayne 3 copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2048,
    height: 2048,
    scale: 1.5,
    trophie_icon: "blur_circular",
    isObj: true
  },
  {
    id: 8,
    title: "Emily Carr",
    description: "...",
    imgAsset: "Student1a copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 4000,
    height: 3000,
    scale: 1,
    trophie_icon: "gradient",
    isObj: true
  },
  {
    id: 9,
    title: "Annabel Cox",
    description: "...",
    imgAsset: "Annabel1 copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2867,
    height: 4096,
    scale: 1,
    trophie_icon: "pause_circle_outline",
    isObj: true
  },
  {
    id: 10,
    title: "Liam Kelleher - That Gallery",
    description: "...",
    imgAsset: "ThatGallery copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 6000,
    height: 2550,
    scale: 1,
    trophie_icon: "photo_album",
    isObj: true
  },
  {
    id: 11,
    title: "Benedict Spiegal",
    description: "...",
    imgAsset: "Students copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 6000,
    height: 2550,
    scale: 1,
    trophie_icon: "grain",
    isObj: true
  },
  {
    id: 12,
    title: "Francesca Joseph",
    description: "...",
    imgAsset: "Student2a copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 6000,
    height: 2550,
    scale: 1,
    trophie_icon: "linear_scale",
    isObj: true
  },
  {
    id: 13,
    title: "Isla Ng",
    description: "...",
    imgAsset: "Studentdd_ copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 4096,
    height: 2867,
    scale: 1,
    trophie_icon: "camera_alt",
    isObj: true
  },
  {
    id: 14,
    title: "Liam Kelleher - Basingstoke Art Class",
    description: "...",
    imgAsset: "BasingstokeArtClass copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 6000,
    height: 2550,
    scale: 1,
    trophie_icon: "android",
    isObj: true
  },
  {
    id: 15,
    title: "Lissie Hacket",
    description: "...",
    imgAsset: "Lissie_ 2 copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2867,
    height: 4096,
    scale: 1,
    trophie_icon: "accessibility",
    isObj: true
  },
  {
    id: 16,
    title: "Louise Quick",
    description: "...",
    imgAsset: "Studentcc_ copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2867,
    height: 4096,
    scale: 1,
    trophie_icon: "group_work",
    isObj: true
  },
  {
    id: 17,
    title: "Liam Kelleher - Willis Museum",
    description: "...",
    imgAsset: "Willis_Museum.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 6000,
    height: 2550,
    scale: 1,
    trophie_icon: "account_balance",
    isObj: true
  },
  {
    id: 18,
    title: "Milena Cholewczuk",
    description: "...",
    imgAsset: "Helena_iPad copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2867,
    height: 4096,
    scale: 1,
    trophie_icon: "directions_car",
    isObj: true
  },
  {
    id: 19,
    title: "Stephanie Quinton",
    description: "...",
    imgAsset: "Lillian-_Let's_Make_A_Deal 2 copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 2867,
    height: 4096,
    scale: 1,
    trophie_icon: "fingerprint",
    isObj: true
  },
  {
    id: 20,
    title: "Liam Kelleher - Viables",
    description: "...",
    imgAsset: "Viable copy.jpg",
    mtlAsset: "3d-model.mtl",
    objAsset: "3d-model.obj",
    width: 6000,
    height: 2550,
    scale: 1,
    trophie_icon: "directions_run",
    isObj: true
  }
];
